FROM golang:1.18.6-alpine3.16 AS builder
RUN apk --no-cache add git make bash
RUN git config --global http.version HTTP/1.1
ADD . /go/src/github/csi-provisioner
WORKDIR /go/src/github/csi-provisioner
RUN make

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="CSI External Provisioner"

COPY --from=builder /go/src/github/csi-provisioner/bin/csi-provisioner csi-provisioner
ENTRYPOINT ["/csi-provisioner"]
